language: generic
branches:
  only:
    - master
cache:
  directories:
    - vendor
env:
  global:
    - IMAGE_PREFIX=deisci
services:
  - docker
sudo: required
install:
  - make bootstrap
script:
  - make test build docker-build
deploy:
  - provider: script
    script: _scripts/stage.sh
    on:
      branch: master
  - provider: script
    script: _scripts/deploy.sh
    on:
      tags: true
