package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/middleware"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/deis/workflow-manager-api/pkg/swagger/models"
)

// NewCreateClusterDetailsForV2Params creates a new CreateClusterDetailsForV2Params object
// with the default values initialized.
func NewCreateClusterDetailsForV2Params() CreateClusterDetailsForV2Params {
	var ()
	return CreateClusterDetailsForV2Params{}
}

// CreateClusterDetailsForV2Params contains all the bound params for the create cluster details for v2 operation
// typically these are obtained from a http.Request
//
// swagger:parameters createClusterDetailsForV2
type CreateClusterDetailsForV2Params struct {
	/*
	  In: body
	*/
	Body *models.Cluster
	/*
	  Required: true
	  In: path
	*/
	ID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *CreateClusterDetailsForV2Params) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	defer r.Body.Close()
	var body models.Cluster
	if err := route.Consumer.Consume(r.Body, &body); err != nil {
		res = append(res, errors.NewParseError("body", "body", "", err))
	} else {
		if err := body.Validate(route.Formats); err != nil {
			res = append(res, err)
		}

		if len(res) == 0 {
			o.Body = &body
		}
	}

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateClusterDetailsForV2Params) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.ID = raw

	return nil
}
