package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-swagger/go-swagger/httpkit/middleware"
)

// CreateClusterDetailsHandlerFunc turns a function with the right signature into a create cluster details handler
type CreateClusterDetailsHandlerFunc func(CreateClusterDetailsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateClusterDetailsHandlerFunc) Handle(params CreateClusterDetailsParams) middleware.Responder {
	return fn(params)
}

// CreateClusterDetailsHandler interface for that can handle valid create cluster details params
type CreateClusterDetailsHandler interface {
	Handle(CreateClusterDetailsParams) middleware.Responder
}

// NewCreateClusterDetails creates a new http.Handler for the create cluster details operation
func NewCreateClusterDetails(ctx *middleware.Context, handler CreateClusterDetailsHandler) *CreateClusterDetails {
	return &CreateClusterDetails{Context: ctx, Handler: handler}
}

/*CreateClusterDetails swagger:route POST /clusters createClusterDetails

create a cluster with all components

*/
type CreateClusterDetails struct {
	Context *middleware.Context
	Handler CreateClusterDetailsHandler
}

func (o *CreateClusterDetails) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewCreateClusterDetailsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
