package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/deis/workflow-manager-api/pkg/swagger/models"
)

/*GetAuthOK authentication response

swagger:response getAuthOK
*/
type GetAuthOK struct {
}

// NewGetAuthOK creates GetAuthOK with default headers values
func NewGetAuthOK() *GetAuthOK {
	return &GetAuthOK{}
}

// WriteResponse to the client
func (o *GetAuthOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
}

/*GetAuthDefault unexpected error

swagger:response getAuthDefault
*/
type GetAuthDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAuthDefault creates GetAuthDefault with default headers values
func NewGetAuthDefault(code int) *GetAuthDefault {
	if code <= 0 {
		code = 500
	}

	return &GetAuthDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get auth default response
func (o *GetAuthDefault) WithStatusCode(code int) *GetAuthDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get auth default response
func (o *GetAuthDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get auth default response
func (o *GetAuthDefault) WithPayload(payload *models.Error) *GetAuthDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get auth default response
func (o *GetAuthDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuthDefault) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
