package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-swagger/go-swagger/httpkit/middleware"
)

// GetAuthHandlerFunc turns a function with the right signature into a get auth handler
type GetAuthHandlerFunc func() middleware.Responder

// Handle executing the request and returning a response
func (fn GetAuthHandlerFunc) Handle() middleware.Responder {
	return fn()
}

// GetAuthHandler interface for that can handle valid get auth params
type GetAuthHandler interface {
	Handle() middleware.Responder
}

// NewGetAuth creates a new http.Handler for the get auth operation
func NewGetAuth(ctx *middleware.Context, handler GetAuthHandler) *GetAuth {
	return &GetAuth{Context: ctx, Handler: handler}
}

/*GetAuth swagger:route GET /auth getAuth

authenticate

*/
type GetAuth struct {
	Context *middleware.Context
	Handler GetAuthHandler
}

func (o *GetAuth) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)

	if err := o.Context.BindValidRequest(r, route, nil); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle() // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
