package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/deis/workflow-manager-api/pkg/swagger/models"
)

/*GetComponentsByLatestReleaseOK component releases response

swagger:response getComponentsByLatestReleaseOK
*/
type GetComponentsByLatestReleaseOK struct {

	// In: body
	Payload GetComponentsByLatestReleaseOKBodyBody `json:"body,omitempty"`
}

// NewGetComponentsByLatestReleaseOK creates GetComponentsByLatestReleaseOK with default headers values
func NewGetComponentsByLatestReleaseOK() *GetComponentsByLatestReleaseOK {
	return &GetComponentsByLatestReleaseOK{}
}

// WithPayload adds the payload to the get components by latest release o k response
func (o *GetComponentsByLatestReleaseOK) WithPayload(payload GetComponentsByLatestReleaseOKBodyBody) *GetComponentsByLatestReleaseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get components by latest release o k response
func (o *GetComponentsByLatestReleaseOK) SetPayload(payload GetComponentsByLatestReleaseOKBodyBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetComponentsByLatestReleaseOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetComponentsByLatestReleaseDefault unexpected error

swagger:response getComponentsByLatestReleaseDefault
*/
type GetComponentsByLatestReleaseDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetComponentsByLatestReleaseDefault creates GetComponentsByLatestReleaseDefault with default headers values
func NewGetComponentsByLatestReleaseDefault(code int) *GetComponentsByLatestReleaseDefault {
	if code <= 0 {
		code = 500
	}

	return &GetComponentsByLatestReleaseDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get components by latest release default response
func (o *GetComponentsByLatestReleaseDefault) WithStatusCode(code int) *GetComponentsByLatestReleaseDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get components by latest release default response
func (o *GetComponentsByLatestReleaseDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get components by latest release default response
func (o *GetComponentsByLatestReleaseDefault) WithPayload(payload *models.Error) *GetComponentsByLatestReleaseDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get components by latest release default response
func (o *GetComponentsByLatestReleaseDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetComponentsByLatestReleaseDefault) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
