package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/deis/workflow-manager-api/pkg/swagger/models"
)

/*GetComponentByReleaseOK component release response

swagger:response getComponentByReleaseOK
*/
type GetComponentByReleaseOK struct {

	// In: body
	Payload *models.ComponentVersion `json:"body,omitempty"`
}

// NewGetComponentByReleaseOK creates GetComponentByReleaseOK with default headers values
func NewGetComponentByReleaseOK() *GetComponentByReleaseOK {
	return &GetComponentByReleaseOK{}
}

// WithPayload adds the payload to the get component by release o k response
func (o *GetComponentByReleaseOK) WithPayload(payload *models.ComponentVersion) *GetComponentByReleaseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get component by release o k response
func (o *GetComponentByReleaseOK) SetPayload(payload *models.ComponentVersion) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetComponentByReleaseOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetComponentByReleaseDefault unexpected error

swagger:response getComponentByReleaseDefault
*/
type GetComponentByReleaseDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetComponentByReleaseDefault creates GetComponentByReleaseDefault with default headers values
func NewGetComponentByReleaseDefault(code int) *GetComponentByReleaseDefault {
	if code <= 0 {
		code = 500
	}

	return &GetComponentByReleaseDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get component by release default response
func (o *GetComponentByReleaseDefault) WithStatusCode(code int) *GetComponentByReleaseDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get component by release default response
func (o *GetComponentByReleaseDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get component by release default response
func (o *GetComponentByReleaseDefault) WithPayload(payload *models.Error) *GetComponentByReleaseDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get component by release default response
func (o *GetComponentByReleaseDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetComponentByReleaseDefault) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
