package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/middleware"
)

// NewGetComponentsByLatestReleaseForV2Params creates a new GetComponentsByLatestReleaseForV2Params object
// with the default values initialized.
func NewGetComponentsByLatestReleaseForV2Params() GetComponentsByLatestReleaseForV2Params {
	var ()
	return GetComponentsByLatestReleaseForV2Params{}
}

// GetComponentsByLatestReleaseForV2Params contains all the bound params for the get components by latest release for v2 operation
// typically these are obtained from a http.Request
//
// swagger:parameters getComponentsByLatestReleaseForV2
type GetComponentsByLatestReleaseForV2Params struct {
	/*
	  In: body
	*/
	Body GetComponentsByLatestReleaseForV2Body
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetComponentsByLatestReleaseForV2Params) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	defer r.Body.Close()
	var body GetComponentsByLatestReleaseForV2Body
	if err := route.Consumer.Consume(r.Body, &body); err != nil {
		res = append(res, errors.NewParseError("body", "body", "", err))
	} else {

		if len(res) == 0 {
			o.Body = body
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
