package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/httpkit/middleware"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetClusterCheckinsParams creates a new GetClusterCheckinsParams object
// with the default values initialized.
func NewGetClusterCheckinsParams() GetClusterCheckinsParams {
	var ()
	return GetClusterCheckinsParams{}
}

// GetClusterCheckinsParams contains all the bound params for the get cluster checkins operation
// typically these are obtained from a http.Request
//
// swagger:parameters getClusterCheckins
type GetClusterCheckinsParams struct {
	/*
	  In: query
	*/
	CreatedAfter *strfmt.DateTime
	/*
	  In: query
	*/
	CreatedBefore *strfmt.DateTime
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetClusterCheckinsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	qs := httpkit.Values(r.URL.Query())

	qCreatedAfter, qhkCreatedAfter, _ := qs.GetOK("created_after")
	if err := o.bindCreatedAfter(qCreatedAfter, qhkCreatedAfter, route.Formats); err != nil {
		res = append(res, err)
	}

	qCreatedBefore, qhkCreatedBefore, _ := qs.GetOK("created_before")
	if err := o.bindCreatedBefore(qCreatedBefore, qhkCreatedBefore, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetClusterCheckinsParams) bindCreatedAfter(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := formats.Parse("date-time", raw)
	if err != nil {
		return errors.InvalidType("created_after", "query", "strfmt.DateTime", raw)
	}
	o.CreatedAfter = (value.(*strfmt.DateTime))

	return nil
}

func (o *GetClusterCheckinsParams) bindCreatedBefore(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := formats.Parse("date-time", raw)
	if err != nil {
		return errors.InvalidType("created_before", "query", "strfmt.DateTime", raw)
	}
	o.CreatedBefore = (value.(*strfmt.DateTime))

	return nil
}
