package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/errors"
)

// NewGetComponentsByLatestReleaseParams creates a new GetComponentsByLatestReleaseParams object
// with the default values initialized.
func NewGetComponentsByLatestReleaseParams() GetComponentsByLatestReleaseParams {
	var ()
	return GetComponentsByLatestReleaseParams{}
}

// GetComponentsByLatestReleaseParams contains all the bound params for the get components by latest release operation
// typically these are obtained from a http.Request
//
// swagger:parameters getComponentsByLatestRelease
type GetComponentsByLatestReleaseParams struct {
	/*
	  In: body
	*/
	Body GetComponentsByLatestReleaseBody
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetComponentsByLatestReleaseParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	defer r.Body.Close()
	var body GetComponentsByLatestReleaseBody
	if err := route.Consumer.Consume(r.Body, &body); err != nil {
		res = append(res, errors.NewParseError("body", "body", "", err))
	} else {

		if len(res) == 0 {
			o.Body = body
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
