package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/deis/workflow-manager-api/pkg/swagger/models"
)

/*GetDoctorInfoOK doctor get response

swagger:response getDoctorInfoOK
*/
type GetDoctorInfoOK struct {

	// In: body
	Payload *models.DoctorInfo `json:"body,omitempty"`
}

// NewGetDoctorInfoOK creates GetDoctorInfoOK with default headers values
func NewGetDoctorInfoOK() *GetDoctorInfoOK {
	return &GetDoctorInfoOK{}
}

// WithPayload adds the payload to the get doctor info o k response
func (o *GetDoctorInfoOK) WithPayload(payload *models.DoctorInfo) *GetDoctorInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get doctor info o k response
func (o *GetDoctorInfoOK) SetPayload(payload *models.DoctorInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDoctorInfoOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetDoctorInfoDefault unexpected error

swagger:response getDoctorInfoDefault
*/
type GetDoctorInfoDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetDoctorInfoDefault creates GetDoctorInfoDefault with default headers values
func NewGetDoctorInfoDefault(code int) *GetDoctorInfoDefault {
	if code <= 0 {
		code = 500
	}

	return &GetDoctorInfoDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get doctor info default response
func (o *GetDoctorInfoDefault) WithStatusCode(code int) *GetDoctorInfoDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get doctor info default response
func (o *GetDoctorInfoDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get doctor info default response
func (o *GetDoctorInfoDefault) WithPayload(payload *models.Error) *GetDoctorInfoDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get doctor info default response
func (o *GetDoctorInfoDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDoctorInfoDefault) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
