package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-swagger/go-swagger/httpkit/middleware"
)

// GetDoctorInfoHandlerFunc turns a function with the right signature into a get doctor info handler
type GetDoctorInfoHandlerFunc func(GetDoctorInfoParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDoctorInfoHandlerFunc) Handle(params GetDoctorInfoParams) middleware.Responder {
	return fn(params)
}

// GetDoctorInfoHandler interface for that can handle valid get doctor info params
type GetDoctorInfoHandler interface {
	Handle(GetDoctorInfoParams) middleware.Responder
}

// NewGetDoctorInfo creates a new http.Handler for the get doctor info operation
func NewGetDoctorInfo(ctx *middleware.Context, handler GetDoctorInfoHandler) *GetDoctorInfo {
	return &GetDoctorInfo{Context: ctx, Handler: handler}
}

/*GetDoctorInfo swagger:route GET /v3/doctor/{uuid} getDoctorInfo

get the specified doctor report as per UUID

*/
type GetDoctorInfo struct {
	Context *middleware.Context
	Handler GetDoctorInfoHandler
}

func (o *GetDoctorInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetDoctorInfoParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
