package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/httpkit/middleware"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetPersistentClustersParams creates a new GetPersistentClustersParams object
// with the default values initialized.
func NewGetPersistentClustersParams() GetPersistentClustersParams {
	var ()
	return GetPersistentClustersParams{}
}

// GetPersistentClustersParams contains all the bound params for the get persistent clusters operation
// typically these are obtained from a http.Request
//
// swagger:parameters getPersistentClusters
type GetPersistentClustersParams struct {
	/*
	  In: query
	*/
	Epoch *strfmt.DateTime
	/*
	  In: query
	*/
	Timestamp *strfmt.DateTime
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetPersistentClustersParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	qs := httpkit.Values(r.URL.Query())

	qEpoch, qhkEpoch, _ := qs.GetOK("epoch")
	if err := o.bindEpoch(qEpoch, qhkEpoch, route.Formats); err != nil {
		res = append(res, err)
	}

	qTimestamp, qhkTimestamp, _ := qs.GetOK("timestamp")
	if err := o.bindTimestamp(qTimestamp, qhkTimestamp, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPersistentClustersParams) bindEpoch(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := formats.Parse("date-time", raw)
	if err != nil {
		return errors.InvalidType("epoch", "query", "strfmt.DateTime", raw)
	}
	o.Epoch = (value.(*strfmt.DateTime))

	return nil
}

func (o *GetPersistentClustersParams) bindTimestamp(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := formats.Parse("date-time", raw)
	if err != nil {
		return errors.InvalidType("timestamp", "query", "strfmt.DateTime", raw)
	}
	o.Timestamp = (value.(*strfmt.DateTime))

	return nil
}
