package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-swagger/go-swagger/httpkit/middleware"
)

// GetClustersCountHandlerFunc turns a function with the right signature into a get clusters count handler
type GetClustersCountHandlerFunc func() middleware.Responder

// Handle executing the request and returning a response
func (fn GetClustersCountHandlerFunc) Handle() middleware.Responder {
	return fn()
}

// GetClustersCountHandler interface for that can handle valid get clusters count params
type GetClustersCountHandler interface {
	Handle() middleware.Responder
}

// NewGetClustersCount creates a new http.Handler for the get clusters count operation
func NewGetClustersCount(ctx *middleware.Context, handler GetClustersCountHandler) *GetClustersCount {
	return &GetClustersCount{Context: ctx, Handler: handler}
}

/*GetClustersCount swagger:route GET /v3/clusters/count getClustersCount

read the count of the known deis clusters

*/
type GetClustersCount struct {
	Context *middleware.Context
	Handler GetClustersCountHandler
}

func (o *GetClustersCount) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)

	if err := o.Context.BindValidRequest(r, route, nil); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle() // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
