package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/middleware"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetDoctorInfoParams creates a new GetDoctorInfoParams object
// with the default values initialized.
func NewGetDoctorInfoParams() GetDoctorInfoParams {
	var ()
	return GetDoctorInfoParams{}
}

// GetDoctorInfoParams contains all the bound params for the get doctor info operation
// typically these are obtained from a http.Request
//
// swagger:parameters getDoctorInfo
type GetDoctorInfoParams struct {
	/*A universal Id to represent a sepcific request or report
	  Required: true
	  In: path
	*/
	UUID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetDoctorInfoParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	rUUID, rhkUUID, _ := route.Params.GetOK("uuid")
	if err := o.bindUUID(rUUID, rhkUUID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetDoctorInfoParams) bindUUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.UUID = raw

	return nil
}
