package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/deis/workflow-manager-api/pkg/swagger/models"
)

/*GetClusterCheckinsOK clusters count response

swagger:response getClusterCheckinsOK
*/
type GetClusterCheckinsOK struct {

	// In: body
	Payload *models.ClustersCount `json:"body,omitempty"`
}

// NewGetClusterCheckinsOK creates GetClusterCheckinsOK with default headers values
func NewGetClusterCheckinsOK() *GetClusterCheckinsOK {
	return &GetClusterCheckinsOK{}
}

// WithPayload adds the payload to the get cluster checkins o k response
func (o *GetClusterCheckinsOK) WithPayload(payload *models.ClustersCount) *GetClusterCheckinsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cluster checkins o k response
func (o *GetClusterCheckinsOK) SetPayload(payload *models.ClustersCount) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClusterCheckinsOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetClusterCheckinsDefault unexpected error

swagger:response getClusterCheckinsDefault
*/
type GetClusterCheckinsDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetClusterCheckinsDefault creates GetClusterCheckinsDefault with default headers values
func NewGetClusterCheckinsDefault(code int) *GetClusterCheckinsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetClusterCheckinsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get cluster checkins default response
func (o *GetClusterCheckinsDefault) WithStatusCode(code int) *GetClusterCheckinsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get cluster checkins default response
func (o *GetClusterCheckinsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get cluster checkins default response
func (o *GetClusterCheckinsDefault) WithPayload(payload *models.Error) *GetClusterCheckinsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cluster checkins default response
func (o *GetClusterCheckinsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClusterCheckinsDefault) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
