package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"

	"github.com/go-swagger/go-swagger/errors"
)

/*ClustersCount clusters count

swagger:model clustersCount
*/
type ClustersCount struct {

	/* count
	 */
	Count *int64 `json:"count,omitempty"`

	/* data
	 */
	Data []*ClusterCheckin `json:"data,omitempty"`
}

// Validate validates this clusters count
func (m *ClustersCount) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClustersCount) validateData(formats strfmt.Registry) error {

	if swag.IsZero(m.Data) { // not required
		return nil
	}

	for i := 0; i < len(m.Data); i++ {

		if m.Data[i] != nil {

			if err := m.Data[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}
